name: tenor_client
description: A Tenor API Client for Dart compatible Web, Flutter, and server-side dart.
version: 0.0.1
author: Saeed Bello <saeed@postagraph.com>
homepage:

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'

dependencies:
  meta: ">=1.1.2 <2.0.0"
  http: ">=0.12.0 <0.13.0"
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.5.0
  mockito: ^4.0.0
  coverage: 
  pedantic: "1.4.0"
  flutter_test:
    sdk: flutter


flutter:
